@startuml
'https://plantuml.com/sequence-diagram

class add_delete_item_controller {
      private AnchorPane item;
      void add_item(ActionEvent event)
      void delete_item(ActionEvent event)
}


@enduml